name = "listing"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-21"

[[rules]]
globs = [ "**/*.wasm" ]
type = "CompiledWasm"

[observability]
enabled = true
head_sampling_rate = 1

[build]
command = "cargo install -q worker-build --version ^0.0.8 && worker-build --release" # required